# Generated by Django 4.1.3 on 2022-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ImageUrl', models.CharField(max_length=100)),
                ('ProjectDescription', models.TextField()),
                ('SourceCode', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
